### ISSUE TITLE
zwin32 fails to build with latest Zig

### ISSUE THREAD

**Issue by hazeycode** [michal-z/zig-gamedev#102]
zwin32 fails to build using the latest Zig compiler (0.10.0-dev.3900+ab4b26d8a)

fn ptr syntax has recently been changed.

**Comment by michal-z** [comment]
Yes, Windows-only part of the project builds only with `-fstage1` atm.
We need to make this code compatible with stage3 compiler.

**Comment by hazeycode** [comment]
I can fixup zwin32 this weekend probably, as a first step

**Comment by michal-z** [comment]
That would be great.

**Comment by marler8997** [comment]
I just pushed a fix for zigwin32 if you want to use it for reference: https://github.com/marlersoft/zigwin32/commit/ff6245cda42adc6c3494bc4d8a5aaaa83c106e30

**Comment by michal-z** [comment]
Nice! Thanks for the info.

**Comment by hazeycode** [comment]
Started https://github.com/michal-z/zig-gamedev/pull/104
