### ISSUE TITLE
Build checks for git submodule assets before pulling

### ISSUE THREAD

**Issue by Pyrolistical** [michal-z/zig-gamedev#120]
git submodules was add in https://github.com/michal-z/zig-gamedev/commit/0b6eed4d8023185cf3171b7cf55dce44838b3d79 but this check occurs before the submodule is pulled down: https://github.com/michal-z/zig-gamedev/blob/main/build.zig#L289

Workaround for now is to manually run:
`git submodule update --init --recursive`

**Comment by michal-z** [comment]
Thanks for the report!
