### ISSUE TITLE
Add custom dawn library path for unprovided binaries

### ISSUE THREAD

**Issue by Pyrolistical** [michal-z/zig-gamedev#121]
[michal-z/dawn-bin](https://github.com/michal-z/dawn-bin) only contains binaries for macOS 12, but I'm still on macOS 11. Fortunately, I can manually build [hexops/mach-gpu](https://github.com/hexops/mach-gpu) using the [`-Ddawn-from-source`](https://github.com/hexops/mach-gpu/blob/main/build.zig#L21).

I managed to hack in the path to `libdawn.a` and got the demos working.

```
diff --git a/build.zig b/build.zig
index 16d8e850..b3394df0 100644
--- a/build.zig
+++ b/build.zig
@@ -8,7 +8,7 @@ pub fn build(b: *std.build.Builder) void {
         .target = b.standardTargetOptions(.{}),
         .ztracy_enable = b.option(bool, "ztracy-enable", "Enable Tracy profiler") orelse false,
     };
-    ensureTarget(b, options.target) catch return;
+    // ensureTarget(b, options.target) catch return;
     ensureZigVersion() catch return;
     ensureGit(b.allocator) catch return;
     ensureGitLfs(b.allocator) catch return;
diff --git a/libs/zgpu/build.zig b/libs/zgpu/build.zig
index 3255f069..78b2fcee 100644
--- a/libs/zgpu/build.zig
+++ b/libs/zgpu/build.zig
@@ -40,7 +40,8 @@ pub fn link(exe: *std.build.LibExeObjStep) void {
         },
         .macos => {
             if (target.cpu.arch.isX86())
-                exe.addLibraryPath(thisDir() ++ "/libs/dawn/x86_64-macos-none")
+                // exe.addLibraryPath(thisDir() ++ "/libs/dawn/x86_64-macos-none")
+                exe.addLibraryPath(".../zig-cache/o/5a4de4a42c82a90b5184bf9ec0cc7908")
             else
                 exe.addLibraryPath(thisDir() ++ "/libs/dawn/aarch64-macos-none");
``` 

Unfortunately, I'm new to zig build and couldn't figure out the proper way to add a `dawn-library-path` build option.

**Comment by michal-z** [comment]
Thanks for the report. Try to use our fork: https://github.com/michal-z/mach-gpu-dawn to build a binary.

I don't really have bandwidth to test and support older macOS versions. Is there a chance that you can upgrade to macOS 12?

**Comment by Pyrolistical** [comment]
I'm on a late 2014 and big sur is the latest supported macos. Let me see if I can do an unsupported install of macos 12

**Comment by michal-z** [comment]
What's the command line to build Dawn for macos 11?
```zig build -Dtarget=x86_64-macos.11```
?

**Comment by michal-z** [comment]
Let me know how it went. If it won't work I can try to add support for macOS 11.

**Comment by Pyrolistical** [comment]
I was able to update to macOS 12 using https://dortania.github.io/OpenCore-Legacy-Patcher/START.html

Just tested the samples and they work!
