### ISSUE TITLE
No member named source in struct std.build.pkig

### ISSUE THREAD

**Issue by jowi-dev** [michal-z/zig-gamedev#122]
Opening for explanation of why I'm also opening a PR :D 

after copying `zmath` into a project I'm working on and building I receive the following error (zig 0.9.1)

`./libs/math/zmath/build.zig:5:5 error: no member named 'source' found in struct 'std.build.Pkg'`

After changing `source` to be `path` the error went away. Do you prefer a fork & merge contribution or are PRs welcome?

Thank you for compiling this resource!

**Comment by michal-z** [comment]
Hi and thanks for the report.

zig-gamedev project follows latest Zig compiler (0.10.x) we don't support older compiler versions.
`path` filed has been re-named to `source`  in 0.10.x and this is what we use.

I highly recommend upgrading to latest Zig.

**Comment by jowi-dev** [comment]
Thank you! out of curiosity are you running nix locally for your env? I had tried to install zig from master but kept getting an error saying my LLVM wasn't on a late enough version.

(feel free to ignore just thought I'd shoot my shot). Thank you again for compiling these resources

**Comment by michal-z** [comment]
I'm working on Windows and I also test on Ubuntu 22.04

Regarding Nix, this may be useful: https://github.com/mitchellh/zig-overlay

**Comment by jowi-papa** [comment]
Interesting. I'm (I am jowi-dev) running POPOS w/ ubuntu 22.04 under it. I'll give it another try today and see. Thanks!
