### ISSUE TITLE
zgpu changes working dir

### ISSUE THREAD

**Issue by meshula** [michal-z/zig-gamedev#126]
Hi all, checkSystem in zgpu.zig accepts a content dir, but changes the dir to where the executable is located. We'd like it to not change the working directory, but to find Roboto-Medium.ttf (and anything else loaded subsequently) to come from the supplied content_dir. We're working around it right now by caching the cwd, allowing zgpu to do its thing, and then restore it, but really, we'd like to have the font in the content_dir, and not have the cwd change. Could that be an option, perhaps?

PS, that 1024 corresponds to MAX_PATH on windows, but PATH_MAX on Linux is typically 4096 or -1 if the path length is unbounded, so that might be a future bug lurking.

```zig
pub fn checkSystem(comptime content_dir: []const u8) !void {
    const doSystemCheck = (struct {
        fn impl() error{ GraphicsApiUnavailable, InvalidDataFiles }!void {
            // TODO: On Windows we should check if DirectX 12 is supported (Windows 10+).
            // On Linux we require Vulkan support.
            if (@import("builtin").target.os.tag == .linux) {
                if (!glfw.vulkanSupported()) {
                    return error.GraphicsApiUnavailable;
                }
                _ = glfw.getRequiredInstanceExtensions() catch return error.GraphicsApiUnavailable;
            }
            // Change directory to where an executable is located.
            {
                var exe_path_buffer: [1024]u8 = undefined;
                const exe_path = std.fs.selfExeDirPath(exe_path_buffer[0..]) catch "./";
                std.os.chdir(exe_path) catch {};
            }
            // Make sure font file is a valid data file and not just a Git LFS pointer.
            {
                const file = std.fs.cwd().openFile(
                    content_dir ++ "Roboto-Medium.ttf",
                    .{},
...            }
        }
    }).impl;
...
```

**Comment by michal-z** [comment]
Hi and thanks for the report.

`checkSystem()` has been removed in the latest version of `zgpu`. It wasn't a good idea to change the dir in a library function. Please update to the latest version if you can.

**Comment by meshula** [comment]
Oh! I didn't notice it had been addressed. I haven't had a close enough eye on commits apparently.

Time to update, thanks for the note!
