### ISSUE TITLE
Proposal for zjobs: a failable tryWait

### ISSUE THREAD

**Issue by Avokadoen** [michal-z/zig-gamedev#128]
Realistically, some code that is executed in parallel might fail. 

## A proposal on how to account for errors:

`schedule`, `Jobid` and `wait` could account for this:
- `schedule` can accept execute functions with a `!void` signature
- `JobId/Fields` can have one bit designated to mark it as a failable job
  - have one storage for non-failable jobs, and one for failable ones 
- if you utilize `tryWait` to wait then you will get the returned error from the execute function in the event that the job failed
  - depending on the complexity of extrapolating the error type, it might be fine to simply accept the exectue error type in the `tryWait` call 
  - using `tryWait` on a non-failable job should probably cause an error to be returned?
 
`prereq` also have to be accounted for. Any job that depend on a failable job is failable with a return type of `error.PrereqFailed`

## Problems with proposal:

- `prereq` is runtime known so validating/checking return type of exec is not feasible. 
- since `tryWait` will have to vary it's return type then type info might have to be turned off (return integer, let the user cast to error) or complex comptime have to be utilized (might not even be possible/feasible).

**Comment by michal-z** [comment]
Thanks for the input. @garettbass what do you think?

**Comment by garettbass** [comment]
I’m not opposed to the idea.  Right now I would instead pass the job a pointer to the output variable, could be any type, including an error, then check that variable after wait.

If we want to store error results from jobs in the job queue for retrieval after a job completes, we have room to do so in a job’s slot, or in an additional result queue.  Caveat being that the error result would be lost the next time that slot index is reused, which happens after `max_jobs` have been executed, should generally be ok.

Should be no need to special case the whole implementation for jobs that do not return an error, just assume all jobs do and wrap exec of those which do not in an inline thunk which returns void (no error).  This can be done inside `Slot.storeJob()` with some `comptime` logic based on the type of `Job.exec()`.  `JobQueue.validateJob()` would be extended to accept `fn(*Job) !void` and `fn(*const Job) !void`.

**Comment by michal-z** [comment]
Windows ThreadPool, enkiTS and Unity Job System all use task functions that always return `void`. I think that we should follow this approach. I would prefer to keep the `zjobs` API simple and report errors via data pointer passed to the job.

@Avokadoen Do you see problems with this solution?

**Comment by Avokadoen** [comment]
I think @gmodarelli's suggestion is a nice workaround for now 👍
