### ISSUE TITLE
zgpu: Memory leak in samples (Dawn leaks ~20KB per frame on macOS)

### ISSUE THREAD

**Issue by Pyrolistical** [michal-z/zig-gamedev#129]
It seems like all the samples have are leaking memory. One can detect this by observing the memory usage of the sample goes up over time.

zig version: 0.10.0-dev.4249+11dce7894
```
$ zig build triangle_wgpu-run      
info: [zgpu] High-performance device has been selected:
info: [zgpu]   Name: Apple M1
info: [zgpu]   Driver: Metal driver on macOS Version 12.6 (Build 21G115)
info: [zgpu]   Adapter type: discrete_gpu
info: [zgpu]   Backend type: meta
```

Here is a capture of the triangle sample's memory usage captured once per second:
```
    48 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
 95216 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
 96368 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
 97424 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
 98512 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
 99504 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
100528 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
101552 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
102544 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
103584 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
104576 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
105584 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
106656 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
107696 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
108720 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
109712 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
110800 michal-z/zig-gamedev/zig-out/bin/triangle_wgpu
```

In Activity Monitor memory usage seems to go up by 40 megabytes per second.

I commented out zgui and the leak remains.

**Comment by Pyrolistical** [comment]
The oldest commit that still runs the triangle demo for me is `c0fcbfd1484d7d943248153533b2e553df291085` and it also leaks memory. I wonder if its env specific. I don't have access to another computer right now.

**Comment by Pyrolistical** [comment]
The memory leaks is faster when the sample isn't being showing on screen. This is likely caused by an extremely high frame rate being off-screen and the memory leak is made more obvious.

I created a [memory-leak branch](https://github.com/Pyrolistical/zig-gamedev/tree/memory-leak) to run the triangle sample with `std.testing.allocator` to see if it catches the problem, but atlas it does not.

Run `zig build test` and it will launch the triangle sample with `std.testing.allocator`.

**Comment by michal-z** [comment]
This is a bug in Dawn and it affects only macOS. This should be fixed after we update to newer Dawn versions.

**Comment by Pyrolistical** [comment]
Thanks. I found it in the issue tracker https://bugs.chromium.org/p/dawn/issues/detail?id=1175

**Comment by michal-z** [comment]
We were discussing this issue on Zig > game-dev channel: https://discord.com/channels/605571803288698900/634812978994085888/1008307672484954213

**Comment by Pyrolistical** [comment]
still leaks memory with
* zig-gamedev 5d64954d7570d336854af1b0fbfbde26fc626c76
* zig 0.11.0-dev.78+28288dcbb

**Comment by michal-z** [comment]
Thanks for the info.

**Comment by foxnne** [comment]
Is there any new news on this? I just had my machine crash after the program used all available app memory for the first time, this bug is still definitely there. 

- zig-gamedev [de7b2bc](https://github.com/michal-z/zig-gamedev/commit/de7b2bcb104496883fcdce0a4a6d717129bcc048)
- zig 0.11.0-dev.2191+30427ff79

**Comment by michal-z** [comment]
Yes, the bug is still there unfortunately. They have decided to fix it after WebGPU 1.0 release (which should happen this Summer).

**Comment by foxnne** [comment]
Gotcha! Thanks for the info!

**Comment by foxnne** [comment]
@michal-z I got a notification that this was fixed I believe, looking at the dawn issue tracker it shows fixed as of 2 days ago. What are the steps to get this into zig-gamedev? I'm itching to get rid of that leak on macOS :D

**Comment by michal-z** [comment]
That's a good news! We need to re-compile and update our Dawn binaries for all platforms. I'm planning to do it in coming weeks.

**Comment by dstrachan** [comment]
Any update on this?

**Comment by foxnne** [comment]
Yes and also if you need any help with anything! I started trying to look at it locally using the latest mach prebuilt but I was getting a lot of errors I didn't know how to solve, but I could look into that further if it would help.

**Comment by meshula** [comment]
Coincidentally our project recently crossed a threshold of usage where this now affects us as well. Previously our app was meant to be used only used for a few minutes at a time, and this didn't break things, now it needs to be run longer.

**Comment by meshula** [comment]
<img width="370" alt="IMG_8315" src="https://github.com/michal-z/zig-gamedev/assets/501238/3b937394-039a-4af6-b83f-25a829704258">

as of 

```
commit eb355bb3edcf7f667597bae78f1be93c70e6297a (HEAD -> main, origin/main, origin/HEAD)
Author: Austin Eng <enga@chromium.org>
Date:   Fri Jul 14 01:10:52 2023 +0000
```

it still leaks, but the rate on my test app has gone from 20mb/s to a few kb/s. So it's gone from unusable to tolerable.

Note also that the dawn build was broken for a couple of days, there was some defunct codegen which they fixed today. The hash I posted here is viable. Hope that saves some time if you are experimenting with an update.

**Comment by michal-z** [comment]
`mach` uses the same lib (`Dawn`) so if a leak is there it will affect every build. That said, `mach` may be using different version than @meshula .

Anyway, I will start working on the update today.

**Comment by meshula** [comment]
I tested with dawn's top of tree as of July 14. The issue is reproducible for us, with the version of zgpu currently referenced by ziggamedev, and all the related zgd demos demonstrate the leak on the several machines we tried, all M1 or M2 based.

**Comment by Pyrolistical** [comment]
@meshula have you reported your findings to google? You can refer to the fix https://bugs.chromium.org/p/dawn/issues/detail?id=1175

**Comment by meshula** [comment]
I think it would make sense to do so after zgpu is updated to latest. Otherwise I am only one data point, and I would be happy to discover that after the zgpu update the problem has been resolved.

**Comment by michal-z** [comment]
Just to let you know, I'm still working on an Dawn update, some changes in `zgpu` are needed so it may takes few more days.

**Comment by michal-z** [comment]
@Pyrolistical @meshula We now have new binaries and @foxnne doesn't see memory leak on macOS anymore. I highly recommend to upgrade.

**Comment by meshula** [comment]
Thanks! We'll upgrade as soon as possible.

**Comment by Pyrolistical** [comment]
Can confirm leak is gone. Thank you.
