### ISSUE TITLE
zjobs: use Thread.Condition instead of sleep?

### ISSUE THREAD

**Issue by Avokadoen** [michal-z/zig-gamedev#130]
I'm just wondering if there is a reason `sleep` is used instead of `ResetEvent` for wait.
Has it been profiled to be faster?

I am willing to try to implement a ResetEvent based wait function if it has not been tested before. 

@garettbass

**Comment by garettbass** [comment]
Thanks for the suggestion.  I am new to zig and was not aware of ResetEvent.  A PR is welcome.  I’m definitely no expert in this area, and just tried to create the simplest thing I could think of that might work.

**Comment by garettbass** [comment]
Having read ResetEvent.zig, I think we could add a ResetEvent to each Slot (storage for pending jobs), we could call `reset` before executing a job, `set` after executing a job, and `waitForSet` instead of `sleep` when there is a `prereq`.  Does that sound right?

**Comment by Avokadoen** [comment]
That sounds right. I double checked what I have used before and Conditions are probably what we want, not ResetEvent (my bad!)

A condition can be signaled and waited on. The tests in the file for Condition should be sufficient but I also used them in this file: https://github.com/Avokadoen/zig_vulkan/blob/main/src/modules/voxel_rt/brick/Worker.zig

Not currently at home to give more context. I'll get working on a prototype tomorrow if you don't want to try and implement it yourself 👍

**Comment by Avokadoen** [comment]
And btw zjobs is even more impressive if this is one of your first Zig projects! 😍

**Comment by michal-z** [comment]
> And btw zjobs is even more impressive if this is one of your first Zig projects! 😍

@garettbass also contributed `zpool` lib. Impressive work. There is also a chance we will get `zentity` some day :)

**Comment by garettbass** [comment]
`zentity` is still in the works.  It is big, so I’m trying to break out smaller sections into useful libs, like `zjobs`.

**Comment by Avokadoen** [comment]
I tried making a prototype for this. It should not be too hard but I see that it is more work than expected to refactor. Like all multithreading there seems to be a few ways to shoot yourself in the foot with this change. I will still look into it, but I'll not prioritize it currently because I have more pressing issues in my hobby project.

**Comment by garettbass** [comment]
Still thinking about this.  Considering having `threadMain` create its own `Condition` instance on its stack, and whenever it finds no jobs waiting, it could insert its own `Condition` into a queue.  Then when a new job is added, we can wake the first `Condition` in that queue, ensuring that one slumbering thread has a chance to pull a job.  I think this would be more energy efficient than each thread spinning/sleeping and checking for more jobs, but the added complexity needs to be carefully considered to avoid bugs or reduced throughput.

**Comment by Avokadoen** [comment]
How will this interact with prereq, either directly or with a combined jobs prereq?

**Comment by Avokadoen** [comment]
@michal-z I'm closing this issue, but I suggest keeping #175. Currently, all threads are woken when a job is scheduled which is wasteful. It would be better if scheduling a job wakes a single idle thread if any.
