### ISSUE TITLE
zgui: Add icon font support for text icons.

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#137]
Small issue, but I was hoping to use font-awesome icons in zgui, [similar to how Prime31 did with zig-upaya](https://github.com/prime31/zig-upaya/blob/master/src/deps/imgui/font_awesome.zig). For any interface it would be nice to have access to icons. 

It looks like [here](https://github.com/prime31/zig-upaya/blob/b040acab13c7af00c3ce0eade03e1f3b0b1d5b02/src/upaya.zig#L222) is a good start.

**Comment by foxnne** [comment]
It looks like [this](https://github.com/ocornut/imgui/issues/232#issuecomment-121622417) is also a useful issue, I'm trying to use [cozette](https://github.com/slavfox/Cozette/blob/master/img/charmap.png) which has some icon glyphs, but it looks like I need to be able to expand the default range using a config passed to `zgui.io.addFontFromFile` to make that work.

**Comment by michal-z** [comment]
I think that all we need here is: `zgui.io.addFontFromFileWithConfig()` which is similar to `zgui.io.addFontFromFile()` but additionally takes `config` and `range'. And then the user should be able to use any glyphs from any font.

To make this happen we need to expose: `ImFontConfig` struct. Do you want to give it a try? As an example you could take a look at `zgui.InputTextCallbackData`.

**Comment by foxnne** [comment]
Sure thing! I actually already got this change working locally and it all seems fine, I'll PR it soon, really appreciate it!

**Comment by Pyrolistical** [comment]
Is there an example on how to use `addFontFromFileWithConfig`? I don't understand how to set the `ranges`.

I'm just trying make `˚` renderable in additional to the default text range.

**Comment by michal-z** [comment]
https://github.com/foxnne/pixi/blob/main/src/pixi.zig#L185

**Comment by Pyrolistical** [comment]
Thanks! That worked for me. I loaded the font with the default range, then merge in the additional range I want.

```
_ = zgui.io.addFontFromFile(
    content_dir ++ "Roboto-Medium.ttf",
    math.floor(20.0 * scale_factor),
);
{
    var config = zgui.FontConfig.init();
    config.merge_mode = true;
    const ranges: []const u16 = &.{ 0x02DA, 0x02DB, 0 };
    _ = zgui.io.addFontFromFileWithConfig(
        content_dir ++ "Roboto-Medium.ttf",
        math.floor(20.0 * scale_factor),
        config,
        ranges.ptr,
    );
}
```
