### ISSUE TITLE
cbullet compile failed on linux

### ISSUE THREAD

**Issue by Jack-Ji** [michal-z/zig-gamedev#14]
Hi @michal-z, I'm trying to compile cbullet on linux/x64, got following error:

```
cbullet.cpp:628:1: error: static_assert failed due to requirement '(sizeof(btTriangleIndexVertexArray) % 16) == 0' "sizeof(btTriangleIndexVertexArray) is not multiple of 16"
cbullet.cpp:814:1: error: static_assert failed due to requirement '(sizeof(btRigidBody) % 16) == 0' "sizeof(btRigidBody) is not multiple of 16"
cbullet.cpp:816:1: error: static_assert failed due to requirement '((sizeof(btRigidBody) + sizeof(btDefaultMotionState)) % 16) == 0' "sizeof(btRigidBody) + sizeof(btDefaultMotionState) is not multiple of 16"
```

My zig version is latest release 0.9.0.

**Comment by michal-z** [comment]
That's interesting. Thanks for the report. I will look at it.

**Comment by michal-z** [comment]
Just double checked it on Windows - it works fine. Can you try changing requirements from 16 to 8?

**Comment by Jack-Ji** [comment]
Sure, I’ll try again tomorrow. BTW, I’m using linkLibC/linkLibCpp instead of linkSystemLibrary("c")/linkSystemLibrary("c++"), which might make some difference here.

**Comment by michal-z** [comment]
I've just checked with linkLibC/linkLibCpp on Windows - still works fine. I didn't know that there is a difference between linkLibC/linkLibCpp and linkSystemLibrary. Do you know more details about this?

**Comment by michal-z** [comment]
BTW, I'm wondering if I could use Zig cross-compilation capabilities to repro this problem on Windows...

**Comment by Jack-Ji** [comment]
My guess is linkLibC/linkLibCpp will use zig’s builtin c/c++ library, which should make cross-compilation more convenient.

**Comment by michal-z** [comment]
Just checked Zig sources, linkSystemLibrary("c") calls linkLibC and linkSystemLibrary("c++") calls linkLibCpp. So, there is no difference.

```
    pub fn linkSystemLibrary(self: *LibExeObjStep, name: []const u8) void {
        if (isLibCLibrary(name)) {
            self.linkLibC();
            return;
        }
        if (isLibCppLibrary(name)) {
            self.linkLibCpp();
            return;
        }
```

**Comment by Jack-Ji** [comment]
Just tried to change several requirements from 16 to 8, compilation is ok now, haven't written any sample code yet.

```
--- ../zig-gamedev/external/src/cbullet.cpp	2021-11-23 17:34:34.388278200 +0800
+++ src/deps/bullet/c/cbullet.cpp	2021-12-24 11:08:44.632513543 +0800
@@ -626,12 +626,12 @@
 
 static_assert((sizeof(btBvhTriangleMeshShape) % 16) == 0, "sizeof(btBvhTriangleMeshShape) is not multiple of 16");
 static_assert(
-    (sizeof(btTriangleIndexVertexArray) % 16) == 0,
-    "sizeof(btTriangleIndexVertexArray) is not multiple of 16"
+    (sizeof(btTriangleIndexVertexArray) % 8) == 0,
+    "sizeof(btTriangleIndexVertexArray) is not multiple of 8"
 );
 static_assert(
-    ((sizeof(btBvhTriangleMeshShape) + sizeof(btTriangleIndexVertexArray)) % 16) == 0,
-    "sizeof(btBvhTriangleMeshShape) + sizeof(btTriangleIndexVertexArray) is not multiple of 16"
+    ((sizeof(btBvhTriangleMeshShape) + sizeof(btTriangleIndexVertexArray)) % 8) == 0,
+    "sizeof(btBvhTriangleMeshShape) + sizeof(btTriangleIndexVertexArray) is not multiple of 8"
 );
 
 void cbtShapeTriMeshCreateBegin(CbtShapeHandle shape_handle) {
@@ -811,11 +811,11 @@
     return shape->getUserIndex2();
 }
 
-static_assert((sizeof(btRigidBody) % 16) == 0, "sizeof(btRigidBody) is not multiple of 16");
+static_assert((sizeof(btRigidBody) % 8) == 0, "sizeof(btRigidBody) is not multiple of 8");
 static_assert((sizeof(btDefaultMotionState) % 16) == 0, "sizeof(btDefaultMotionState) is not multiple of 16");
 static_assert(
-    ((sizeof(btRigidBody) + sizeof(btDefaultMotionState)) % 16) == 0,
-    "sizeof(btRigidBody) + sizeof(btDefaultMotionState) is not multiple of 16"
+    ((sizeof(btRigidBody) + sizeof(btDefaultMotionState)) % 8) == 0,
+    "sizeof(btRigidBody) + sizeof(btDefaultMotionState) is not multiple of 8"
 );
 
 CbtBodyHandle cbtBodyAllocate(void) {
```

**Comment by michal-z** [comment]
Thanks! It should work I think. I will make sure and set it to 8 in main branch.

**Comment by michal-z** [comment]
I've changed requirements to 8. It is enough, all should work fine. Please let me know once you get it running on Linux.

**Comment by michal-z** [comment]
@Jack-Ji Any news regarding this?

**Comment by Jack-Ji** [comment]
Sorry it took so long, you know, busy jobs. I just began writing the sample
code, hopefully can be done within 24 hours.

Michal Ziulek ***@***.***>于2022年1月6日 周四00:52写道：

**Comment by michal-z** [comment]
@Jack-Ji  Sure, no rush. Thanks!

**Comment by Jack-Ji** [comment]
Hi @michal-z, just finished a sample, collision test works perfect. Although Constraint isn't tested, I think it's safe to close the issue.
![image](https://user-images.githubusercontent.com/1416077/148375692-12a39eaa-54b2-4d89-950e-96f07187d788.png)

**Comment by michal-z** [comment]
@Jack-Ji Great, thanks for the info!

**Comment by Jack-Ji** [comment]
Yeah, it’s open repo on github, feel free to check out. Though it’s not mature enough to do serious work yet, cause I’m really a newbie in gamedev territory :-)
https://github.com/Jack-Ji/zplay
