### ISSUE TITLE
zmesh: Shape.unweld eliminate texture coordinates

### ISSUE THREAD

**Issue by Jack-Ji** [michal-z/zig-gamedev#140]
Hi michal, as suggested by title of issue, I've noticed shape's texture coordinates becomes null after called Shape.unweld. Is it mandatory or configurable?

**Comment by michal-z** [comment]
Yes, currently it removes normals and texcoords. There was a bug in the `par_shapes` library that caused crashes, I did a simple fix that removes those attributes. Note that normals can be easily regenerated with `computeNormals()` but texcoords are lost.

It should be pretty easy to handle texcoords correctly in `par_shapes_unweld()` C functions I think. We would have to copy them to each new vertex (similar to how points are handled). Do you want to give it a try?

**Comment by Jack-Ji** [comment]
Sure! I'll take a stab.

**Comment by michal-z** [comment]
I actually did it but I'm not sure if it works correctly. Please take a look/test.

**Comment by Jack-Ji** [comment]
I just reviewed and tested unweld operation, my sample works fine. Thank you for quick response!
