### ISSUE TITLE
How to setup frame debug tools?

### ISSUE THREAD

**Issue by Pyrolistical** [michal-z/zig-gamedev#143]
Dawn offers debug markers https://dawn.googlesource.com/dawn/+/refs/heads/chromium/4527/docs/debug_markers.md

I tried setting up Microsoft PIX, but couldn't the project to run with WinPixEventRuntime. Copied both the .dll and .lib into `zig-gamedev/libs/zgpu/libs/dawn/x86_64-windows-gnu` but it didn't work.

I was able to run the project with Intel Graphics Frame Analyzer, but crashed when a frame capture is attempted.

For Metal, it requires the project to be run from XCode. Is that possible with zig-gamedev?

I also tried https://developer.nvidia.com/nsight-graphics and was able to run a zig-gamedev project with it, but when I tried to capture a frame, it crashed.

Is there a known good setup?

**Comment by michal-z** [comment]
To capture a frame you can just run your application from PIX - it worked for me. WinPixEventRuntime is needed only if you want to mark "scopes" with `pushDebugGroup` and `popDebugGroup` (dll should be placed next to your app exe).

**Comment by Pyrolistical** [comment]
Thanks! I got PIX to work. You need to launch the project with PIX in order to capture frames. Attach to running process doesn't work.
