### ISSUE TITLE
Unable to link zmesh

### ISSUE THREAD

**Issue by raegnar** [michal-z/zig-gamedev#144]
Maybe I'm missing something basic, but I'm for some reason getting link errors when trying to link zmesh

```
MachO Flush... error(link): undefined reference to symbol '_zmeshCalloc'
error(link):   first referenced in '/Users/raegnar/cerberus/zig-cache/o/a588170dd6d74e3a6551d04e63cc9bfd/par_shapes.o'
error(link): undefined reference to symbol '_zmeshRealloc'
error(link):   first referenced in '/Users/raegnar/cerberus/zig-cache/o/a588170dd6d74e3a6551d04e63cc9bfd/par_shapes.o'
error(link): undefined reference to symbol '_zmeshMalloc'
error(link):   first referenced in '/Users/raegnar/cerberus/zig-cache/o/a588170dd6d74e3a6551d04e63cc9bfd/par_shapes.o'
error(link): undefined reference to symbol '_zmeshFree'
error(link):   first referenced in '/Users/raegnar/cerberus/zig-cache/o/a588170dd6d74e3a6551d04e63cc9bfd/par_shapes.o'
error: UndefinedSymbolReference
```

Following all the instructions and steps as including any other zig-gamedev library, but this is the only one giving me trouble.

```
const zmesh = @import("ext/zig/zig-gamedev/libs/zmesh/build.zig");

...

const zmesh_options = zmesh.BuildOptionsStep.init(builder, .{});
const zmesh_pkg  = zmesh.getPkg(&.{zmesh_options.getPkg()});

exe.addPackage(zmesh_pkg);

...

zmesh.link(exe, zmesh_options);
```

Am I missing something obvious?

**Comment by michal-z** [comment]
Looks like you don't reference `zmesh` in your code and memory functions are not compiled. Do you call any of `zmesh` function?
Or try to add below code:

```zig
const zmesh = @import("zmesh");

test {
    _ = zmesh;
}
```

**Comment by raegnar** [comment]
Yup, that was it, I falsely assumed I had to deal with the linker issue _before_ importing and using zmesh, which is what actually was causing the issue.
Thanks for the help!

**Comment by raegnar** [comment]
Okay, that was pretty much it, I had falsely assumed I need to address the linker issue _before_ actually using zmesh, when in actuality the linker issue would remain _until_ I used zmesh.

Thanks for your help!
