### ISSUE TITLE
zaudio: mismatch SoundImpl.createCopy function signature

### ISSUE THREAD

**Issue by Pyrolistical** [michal-z/zig-gamedev#146]
The call site passes in an `allocator`
```zig
return SoundImpl.createCopy(allocator, engine, existing_sound, flags, sgroup);
```
https://github.com/michal-z/zig-gamedev/blob/main/libs/zaudio/src/zaudio.zig#L1687

But isn't defined on the implementation
```zig
fn createCopy(engine: Engine, existing_sound: Sound, flags: SoundFlags, sgroup: ?SoundGroup) Error!Sound {
```
https://github.com/michal-z/zig-gamedev/blob/main/libs/zaudio/src/zaudio.zig#L1908

I tried to fix it, but I then ran into some `unreachable` code and couldn't figure out where it was coming from.

**Comment by michal-z** [comment]
Thanks for the info. I've fixed the mismatch.

Note, that:
"Cloning only works for data buffers (not streams) that are loaded from the resource manager."

In all other cases this function will report `InvalidOperation` error.

**Comment by Pyrolistical** [comment]
i didn't use it in the end. but thanks
