### ISSUE TITLE
Is there currently a way to define how images are presented in zgui?

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#147]
Hi!

Currently I am trying to implement zooming into a project that draws textures using zgui.

However, when zooming, textures become very blurry. 
<img width="1392" alt="Screen Shot 2022-10-27 at 10 02 45 PM" src="https://user-images.githubusercontent.com/49629865/198488683-4cee05d9-c6f4-4dde-ace3-0b5745f9c4d4.png">

Is there a way to, either when drawing using `zgui.image()` or `draw_list.addImage()`, use point scaling when drawing the images to keep crisp pixels?

Thanks for any info!

**Comment by michal-z** [comment]
Hi,

Using nearest filtering is actually not supported in imgui, see here: https://github.com/ocornut/imgui/issues/5118

"At a high level there are two strategies:

A) Use ImGuiDrawList::AddCallback to insert a callback to change the texture filtering to nearest neighbor, draw your image, and then call AddCallback(ImDrawCallback_ResetRenderState) to reset the state.
B) Use ImGuiDrawList::AddCallback to manually draw your image with nearest neighbor. (Being sure not to affect global state or use ImDrawCallback_ResetRenderState again to reset it.)"

We will need to expose `ImGuiDrawList::AddCallback` and then you would have to draw your image with nearest filtering manually.

As an alternative, you could draw those images yourself (not using zgui but just wgpu) onto zgui window.

What do you think?

**Comment by foxnne** [comment]
Yeah, that's pretty much the same conclusion I came to last night. I looked at drawing the images outside of zgui, but I feel like it would end up being a mess trying to clip the image to the child window for the canvas with scroll bars and all of that, and that keeping the image rendering within zgui would be best.

I'll look at exposing `ImGuiDrawList::AddCallback` and try to get it working in my project and then I'll get you a PR.

Thanks!

**Comment by michal-z** [comment]
You will need to bind your custom rendering pipeline and sampler with nearest filtering and the issue a draw call.

**Comment by foxnne** [comment]
Would it be any simpler for me to somehow just render _all_ zgui as nearest neighbor through zgpu? I'm a bit confused that I didn't run into this issue on the previous iteration of Pixi, I suppose [upaya](https://github.com/foxnne/zig-upaya) renders all imgui stuff with nearest neighbor...

**Comment by michal-z** [comment]
Try to change filtering method here:
https://github.com/michal-z/zig-gamedev/blob/main/libs/zgui/libs/imgui/imgui_impl_wgpu.cpp#L534

**Comment by foxnne** [comment]
This works!

**Comment by michal-z** [comment]
This also affect text rendering, right? Does it look nice?

**Comment by foxnne** [comment]
<img width="1392" alt="Screenshot 2022-10-28 at 11 20 13 AM" src="https://user-images.githubusercontent.com/49629865/198685319-133438fd-9fa1-4b1f-8508-1f5e8f75dcf1.png">

For me, it looks great, but I'm using a "pixely" font, so I would honestly prefer this font be nearest neighbor as well.

**Comment by michal-z** [comment]
Looks very nice indeed! I think we should have an option to switch between samplers.

**Comment by foxnne** [comment]
I'm not sure how to accomplish that without editing `imgui_impl_wgpu.cpp`, would you like me to still look into the `callback` route? Or do you have an idea to provide that option?

**Comment by michal-z** [comment]
I will think about it some more - the simplest solution would be to provide an option in `zgui.backend.init()`. I will solve this issue next week.

**Comment by michal-z** [comment]
@foxnne I've added `zgui.backend.initWithConfig()` which lets you select `nearest` texture filtering mode. Please take a look at `gui_test_wgpu` demo how to use it.

**Comment by foxnne** [comment]
Fantastic, thank you so much for adding this!

**Comment by michal-z** [comment]
@foxnne Can we close this issue?

**Comment by foxnne** [comment]
Oh, my bad, closing!
