### ISSUE TITLE
How to pass a dynamic string to zgui widget

### ISSUE THREAD

**Issue by raegnar** [michal-z/zig-gamedev#149]
How can I pass a dynamically created label to a widget, in this case `zgui.collapsingHeader`, I am constantly getting an error message:

`error: expected type '[:0]const u8', found '[]u8'`

Where the string being passed to collapsing header is created with `allocPrint`.

```
var label = try std.fmt.allocPrint(
    allocator,
    "node {}",
    .{ node.index },
);

if (zgui.collapsingHeader(label, .{}))
{
    ...
}
```

I've tried a bunch of other ways to do this to no avail.

**Comment by michal-z** [comment]
You can use `zgui.formatZ()`:

```zig
if (zgui.collapsingHeader(zgui.formatZ("node {}", .{node.index}), .{})) {
    ...
}
```

**Comment by raegnar** [comment]
Works! Thanks!
