### ISSUE TITLE
Error when trying to run the example

### ISSUE THREAD

**Issue by n4skx** [michal-z/zig-gamedev#154]
My current operational system: **Windows 10 10.0.22000.1098**

What i tried to run:
```
$ git clone https://github.com/michal-z/zig-gamedev.git
$ cd zig-gamedev
$ zig build physically_based_rendering_wgpu-run
```

So then it gives me a error:
```
Illegal instruction at address 0x7ff76cfd1010
0x7ff73157a106 in OpenFile (build.exe.obj)
        .OBJECT_PATH_NOT_FOUND => return error.FileNotFound
```

Maybe i miss some step to run this example?

**Comment by michal-z** [comment]
It should work fine. What Zig version do you use? Try to delete `zig-cache` folder and build again.

**Comment by n4skx** [comment]
Hi, i'm using zig 0.10-dev.

**Comment by n4skx** [comment]
After doing that it gives me new errors:

```
Illegal instruction at address 0x7ff7305c1630
The following command exited with error code 3 (expected 0):
cd C:\Users\Ukn0w404\Documents\zig-gamedev && C:\Users\Ukn0w404\Documents\zig-gamedev\zig-out\bin\triangle_wgpu.exe
error: UnexpectedExitCode
C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.10.0\lib\std\build\RunStep.zig:277:17: 0x7ff6f5c0b90f in runCommand (build.exe.obj)
                return error.UnexpectedExitCode;
                ^
```

**Comment by michal-z** [comment]
Looks very strange, like a corrupted build script.

Could you try official Zig builds from: https://ziglang.org/download/0.10.0/zig-windows-x86_64-0.10.0.zip

Also, try to re-clone the repo.

**Comment by michal-z** [comment]
I've just re-tested with Zig 0.10.0 official build on Windows and all works fine for me.

**Comment by n4skx** [comment]
Ohh, i have sayed Windows 10 but i'm currently in windows 11 tho

**Comment by n4skx** [comment]
i tried to re-install zig on it but doesn't work again

**Comment by n4skx** [comment]
After a time debugging i found this instruction causing the error:
![image](https://user-images.githubusercontent.com/117673364/200385464-037ab061-0e4e-45c4-bc67-237b371f587f.png)

So the error is when calling ``dawn::native::InstanceBase::InstanceBase``
![image](https://user-images.githubusercontent.com/117673364/200385741-58cda310-4cb3-427f-bd08-e56e327bdd60.png)

**Comment by michal-z** [comment]
I'm also using Windows 11.
Could you take a look at `libs/zgpu/libs/dawn/x86_64-windows-gnu/dawn.lib` file? What is the exact size of it?

It should be: 38.5 MB (40,385,442 bytes)

**Comment by michal-z** [comment]
Ok, I know what is happening. Dawn binaries use AVX/AVX2 instruction set and your CPU does not support it. I will upload new binaries that don't require AVX/AVX2.

**Comment by n4skx** [comment]
Thanks!

**Comment by michal-z** [comment]
It should work now, please fetch the latest code and re-build.

**Comment by n4skx** [comment]
It worked!!!! Thanks!
