### ISSUE TITLE
zstbi: Add support for HDR images in `Image.loadFromMemory()`

### ISSUE THREAD

**Issue by michal-z** [michal-z/zig-gamedev#155]
Similarly how it is done in `Image.loadFromFile()`.

**Comment by soenkekrusche** [comment]
is this issue still relevant? I can't seem to find Image.initFromData() or Image.init()

**Comment by michal-z** [comment]
Yes it is relevant. Those functions have been renamed:
`Image.init()` -> `Image.loadFromFile()`
`Image.initFromData()` -> `Image.loadFromMemory()`

Thanks for pointing it out!

**Comment by soenkekrusche** [comment]
As this is marked as "good first issue" I tried to provide my good first contribution - feedback welcome https://github.com/michal-z/zig-gamedev/pull/231

**Comment by michal-z** [comment]
Implemented in https://github.com/michal-z/zig-gamedev/pull/231
