### ISSUE TITLE
zgpu: Crash when minimizing window on Windows

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#156]
Hi! 

I haven't had a chance to test macos, but on Windows I'm getting a crash when trying to minimize the window, both in my project and with the example `gui_test_wgpu`. 
```
error: [zgpu] Validation: Swap Chain size (width: 0, height: 0) is empty.
 - While validating [SwapChainDescriptor "main window swap chain"]
 - While calling [Device].CreateSwapChain([SwapChainDescriptor "main window swap chain"]).
 ```

I can try to look into this when I get some free time. Looks like maybe we don't handle a case where the swap chain is 0 sized.

**Comment by foxnne** [comment]
Tested on macOS and no crash, looks like it may be Windows specifically passing a window resized event with 0 sized dimensions?

**Comment by michal-z** [comment]
@foxnne It now works fine on Windows, could you also verify macOS?

**Comment by foxnne** [comment]
Works fine on macOS, thanks for the fix!
