### ISSUE TITLE
zgui: Possible issue tied to dawn memory leak on macOS

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#157]
Issue backstory here: https://github.com/foxnne/pixi/issues/9

I haven't been able to repro this outside of my project yet, but I also haven't had much time to investigate. Just creating this issue from what we talked about on Discord. 

I'm using [this zip library](https://github.com/kuba--/zip), and if I use zgui and load a zip file triggered from a selectable, 9/10 times it works fine, but sometimes the program freezes and begins flashing a magenta screen. If I resize the window during this, the magenta screen stays on screen with no flashing. The program cannot recover and will stay magenta until it is closed. No errors are reported. This only occurs on macOS.

Googling around for similar issues doesn't turn up much, but I did see a couple mentions that sometimes shader errors are presented with a magenta screen using Dear Imgui, but its fully possible this is an issue popping up from something else and just presenting as a shader error through zgui.

**Comment by michal-z** [comment]
Note that `Image.initFromData()` do not copy the data but keeps a reference to it. My guess - below code allocates the data and then releases it with `defer` code but `image` still keeps a reference to it. What do you think?

```zig
     _ = zip.zip_entry_open(pixi_file, layer_image_name.ptr); 
     _ = zip.zip_entry_read(pixi_file, &img_buf, &img_len); 
     defer _ = zip.zip_entry_close(pixi_file); 
```

**Comment by foxnne** [comment]
Thanks! I just modified my code to use ```allocator.dupe()``` and store the raw data rather than letting it release at the end of the load scope, I'll try this out for a while and see if it remedies the bug.

**Comment by foxnne** [comment]
Looks like this change fixed the issue, thank you so much for your help and apologies for the false alarm!

**Comment by michal-z** [comment]
Great to here that! Happy I could help.
