### ISSUE TITLE
It looks like tracy integrations has issues with names and colors

### ISSUE THREAD

**Issue by SentientNr6** [michal-z/zig-gamedev#16]
Hi,

I was trying the tracy integration but it seems to work different than expected. Having never used tracy before and being new to Zig I might be doing something wrong though.

When I extend the intro2 sample with the following (silly) code 

```
// Draw dear imgui widgets (not used in this demo).
    {
        if (true) {
            const tracy_zone = tracy.zoneNC(@src(), "B", 0x00ffff00, 1);
            defer tracy_zone.end();
            {
                {
                    const tracy_zone1 = tracy.zoneNC(@src(), "B1", 0x0000ff00, 1);
                    defer tracy_zone1.end();
                    std.time.sleep(std.time.ns_per_ms * 20);
                }
                {
                    const tracy_zone2 = tracy.zoneNC(@src(), "B2", 0x000000ff, 1);
                    defer tracy_zone2.end();
                    std.time.sleep(std.time.ns_per_ms * 30);
                }
            }

            std.time.sleep(std.time.ns_per_ms * 50);
        }
        demo.guictx.draw(gctx);
    }
```

I get the following-> 

![image](https://user-images.githubusercontent.com/68496371/149675315-ceb0c68c-93d4-464d-ae24-bbb49c158997.png)

The timings, lengths of the bars, are OK but the names and colors not. 
The behavior isn't the same al the time though. Sometimes it work as intended and sometimes it shows "?" as names. But the image above is what I get most often.

Apart from that I am really impressed by what I have seen of your work.

**Comment by michal-z** [comment]
Hi and thanks for the report. I will look at it tomorrow. Do you use Tracy 0.7.8 or some newer build from master branch?

**Comment by SentientNr6** [comment]
Thanks Michal, I use Tracy 0.7.8 release.

**Comment by michal-z** [comment]
Colors and names are fine in debug builds but breaks as you report in ```-Drelease-fast=true``` builds. I will investigate it further.
