### ISSUE TITLE
zmath: Make all fns pub for using zmath as a math backend

### ISSUE THREAD

**Issue by maihd** [michal-z/zig-gamedev#169]
I'm creating a simple [game framework](https://github.com/maihd/gamefx) for 2D mobile game. But I found that `zmath` does not support `@Vector2(2, f32)`.

There is a solution for fast implemenetation is cos32xN (and friends), but theses fns are private. Can you make its `pub`?

Below code encounter `error: 'cos32xN' is not marked 'pub'`:
```zig
pub fn cos(v: anytype) @TypeOf(v) {
    const T = @TypeOf(v);
    return switch (T) {
        f32, types.f32x4, types.f32x4x4 => zmath.cos(v),
        types.f32x2, types.f32x3 => zmath.cos32xN(v),
        else => @compileError("gamefx.math.sin() not implemented for " ++ @typeName(T)),
    };
}
```

**Comment by michal-z** [comment]
We could expose `F32x2` type but remember that HW would still use SIMDx4 ops underneath. Generally, you should keep your vector data as `[2]f32` and load it to the HW register only for computation.

```zig
const pv = zm.loadArr2(game_object.position);
// do computations
zm.storeArr2(...);
```
Currently we do not implement `zm.loadArr2()` and `zm.storeArr2()` but I will add it.

**Comment by maihd** [comment]
In zig 0.10.0 (my current zig version), `f32x2` is [2]f32. Below code proof it:
```zig
comptime {
    const assert = @import("std").debug.assert;
    assert(@sizeOf(f32x2) == 2 * @sizeOf(f32));
    assert(@sizeOf(f32x3) == 4 * @sizeOf(f32));
    assert(@sizeOf(f32x4) == 4 * @sizeOf(f32));
}
```

**Comment by michal-z** [comment]
You would still have operator overloading working:
```zig
const pv = zm.loadArr2(game_object.position);
// pv is aF32x4 you can use operator overloading and do your computation here
// when you are done store 'x' and 'y' components as a result
zm.storeArr2(...);
```

**Comment by maihd** [comment]
Ah that the case! We cannot sure `@sizeOf(@Vector(2, f32))` is always `2 * @sizeOf(f32)`.

Thanks you.

**Comment by michal-z** [comment]
Yes, exactly. `@Vector` is basically an abstraction for CPU SIMD register and it has fixed size.

**Comment by michal-z** [comment]
We actually already have `loadArr2()` and `storeArr2()`.

**Comment by maihd** [comment]
Great!

**Comment by maihd** [comment]
Ah, there are a problem, when I passing `F32x2` to raylib, can I `@bitCast`, instead of construct new `raylib.Vector2`?

**Comment by maihd** [comment]
Okay👌

**Comment by michal-z** [comment]
Can we close this issue?

**Comment by maihd** [comment]
Yes!
