### ISSUE TITLE
Question: what are the criteria for getting a function into zmathlib?

### ISSUE THREAD

**Issue by francescoalemanno** [michal-z/zig-gamedev#17]
Hallo!! Very nice work 💯 

I wanted to contribute a few fast approximation for common mathematical functions, 
what is the required accuracy for a math function to be accepted into zmath?

Kindest regards,
Francesco

**Comment by michal-z** [comment]
Hi and thanks!

There are no strict accuracy requirements - we tend to follow DirectXMath C++ library. We can have two versions of the same function, for instance, maxFast(), max(), sin(), sinFast(), etc.

Thanks for interest, feel free to submit PR and we can review/discuss further.

**Comment by francescoalemanno** [comment]
```zig

fn fasterf(sx: f64) f64 {
    if (sx > 4) return 1.0;
    if (sx < -4) return -1.0;
    const x = std.math.absFloat(sx);
    const num: f64 = @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, 0.0028593219226644576, 0.01867154530943367), 0.17638805124167325), -0.46076304644159816), 1.1283761621012647);
    const den: f64 = @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, 0.06458056352180008, -0.11865383943204451), 0.48953081894249706), -0.40836823383711635), 1.0);
    return sx * num / den;
}

fn fasttanh(sx: f64) f64 {
    if (sx >= 7) return 1.0;
    if (sx <= -7) return -1.0;
    const x = std.math.absFloat(sx);
    const num: f64 = @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, 0.004900740897321849, 0.02790273545044266), 0.14825256448360716), 0.2416666803684097), 1.0000002029961501);
    const den: f64 = @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, @mulAdd(f64, x, 0.004785854808954178, 0.031224079735785348), 0.10893724058162953), 0.4814584737831293), 0.2416793613234902), 1.0);
    return sx * num / den;
}

```

very roughly, I took this out of my hyper small mathlib, as soon as I find time I'll make a f32 version and prepare a PR

**Comment by michal-z** [comment]
Looks fine, thanks.
Note, that zmath is mostly about vectorized versions. Would you be able to SIMD-ify those?

**Comment by michal-z** [comment]
@francescoalemanno Hi, do you still plan to work on this or should I close the issue?

**Comment by michal-z** [comment]
Closing for now - feel free to re-open.
