### ISSUE TITLE
Drawing multiple quads with transparent textures become independently more opaque (wgpu)

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#194]
Just filing this issue in case I can track down any extra information, as this would likely affect anyone attempting to work in 2D and use sprites with transparency. 

I have added a PR (#193) that has a pretty minimal way to observe the behavior.

**Description**:
When drawing simple quads using a texture with alpha between 0 and 255, additional quads seem to stack up the alpha regardless of if the quads are overlapping. Attached are screenshots but it may not be as obvious in them. 

This issue has been observed on both arm64 macOS and Windows.

<img width="1712" alt="Screenshot 2023-01-25 at 12 09 05 AM" src="https://user-images.githubusercontent.com/49629865/214492950-f7d38058-5d54-4f14-8336-e7a2b020b4f0.png">
<img width="1712" alt="Screenshot 2023-01-25 at 12 09 09 AM" src="https://user-images.githubusercontent.com/49629865/214492959-fecdf688-37fc-4c49-90a0-befec4fd4398.png">

**Comment by michal-z** [comment]
Thanks for the issue. I forgot about this problem. Will be looking at it today, sorry for the delay.
