### ISSUE TITLE
Question: Is zmath deterministic?

### ISSUE THREAD

**Issue by castholm** [michal-z/zig-gamedev#200]
If possible, I want to use zmath for a replay system in a game, so that you can download a replay from another player, replay their inputs and get the exact same result.

Assuming the same zmath version and no messing with `-ffast-math`/`@setFloatMode()`/IEEE rounding modes/flush to zero, are all zmath calculations deterministic across different platforms and architectures?

**Comment by michal-z** [comment]
With one exception (see below) `zmath` should be fully deterministic. We don't have tests for determinism though.

Currently, for performance reasons we use HW `fma` instructions on x86 CPUs that support AVX instruction set. But, on CPUs that don't support AVX we use mul add sequence. `fma` is faster and more accurate (one rounding).

Please take a look at `mulAdd()` function: https://github.com/michal-z/zig-gamedev/blob/main/libs/zmath/src/zmath.zig#L1408

To make the code fully deterministic we would have to unify this code.

Note that compiler won't generate `fma` instructions by itself you have to explicitly tell it to do so by using @mulAdd instrinsic.

**Comment by castholm** [comment]
Great, thanks for the info.

For now, if I absolutely need cross platform determinism I could just edit `mulAdd()` in my copy of the lib to always multiply and add separately. But would adding ways for the consumer to more easily choose between speed or determinism (such as via alternative functions or build options) fall in line with your vision for zmath? Or is speed the only goal and determinism just an added bonus?

**Comment by michal-z** [comment]
Yes, we should have a build option for this. There are some breaking changes in Zig build system coming (https://github.com/ziglang/zig/pull/14498) - adapting our code to this change will be a good opportunity to add this option. I will do it in coming days.

**Comment by michal-z** [comment]
We now have a `prefer_determinism` build option:

build.zig:
```zig
const zmath_pkg = zmath.package(b, .{ 
    .options = { .prefer_determinism = true },
});
exe.addModule("zmath", zmath_pkg.module);
```

**Comment by castholm** [comment]
@castholm Yes. Thanks you for your hard work!
