### ISSUE TITLE
Jolt Physics Debug Renderer

### ISSUE THREAD

**Issue by a-day-old-bagel** [michal-z/zig-gamedev#259]
Jolt Physics allows for a debug renderer. I don't see any of this having come across to the zig API yet, though, right? Or am I just missing it?

Is this something to be done (maybe even I could give it a shot and PR), or something that is left out for a reason?

**Comment by michal-z** [comment]
You are correct, we don't have it yet. PR is very welcome.

**Comment by a-day-old-bagel** [comment]
I haven't yet figured out a clean-feeling way to turn on and off parts of code in zig like you can do in C with #ifdef. Short of conditionally appending fields to a type, which seems hack-y, I'm not sure how to exclude debug draw logic from the compilation based on a build option.

And maybe it doesn't matter, and I can just leave it in the code even if the option is turned off (and maybe the compiler will realize it's a dead branch and cut it out itself), but I wasn't sure what the project required as far as best practices for something like this.

**Comment by michal-z** [comment]
Compiler won't figure it out - we need to do conditional compiling.

Something like below should work:

`my_debug_field: if (debug_renderer) u32 else void,`

**Comment by a-day-old-bagel** [comment]
Ok sounds good. That's more or less the direction I went in, lacking any better ideas. I'll check back in if any more questions arise. Trying to find time to finish it up still.

**Comment by a-day-old-bagel** [comment]
I had a question about the C typedefs:

In Jolt proper, types such as `RVec3` are defined as helpers to mean an array of 3 "Reals," where Real is `float` or `double` depending on the precision define set by the user.

In JPC, though I see the Real arrays just being left explicit, as in `const JPC_Real in_base_offset[3]`, when I expect it should be possible to make the same sort of typedefs that you see in Jolt proper. For example, by adding the last two lines after the exiting precision ifdef in JoltPhysicsC.h, like so:

```#if JPC_DOUBLE_PRECISION == 1
typedef double JPC_Real;
#define JPC_RVEC_ALIGN alignas(32)
#else
typedef float JPC_Real;
#define JPC_RVEC_ALIGN alignas(16)
#endif

typedef JPC_Real[3] JPC_RVec3
typedef JPC_Real[16] JPC_RMat44Arg```

Is there a reason this hasn't been done, and could I do it for the code I add, or would it be better to keep doing it explicitly to remain consistent, OR would it be better to change existing code to use a new typedef?

I know it's not a big deal probably, but I wanted to check in.

**Comment by a-day-old-bagel** [comment]
@michal-z Would you mind taking just a moment to explain why you set up PhysicsSystemData as an appendage to the PhysicsSystem object from JPH? I'm trying to figure out if I should be using that for the debug renderer similarly to how it's used for the contact listener.

Failing that, I had just been planning to make some extra assumptions for the C port, based on the fact that the JPH debug renderer is a singleton, and probably end up with a private global vtable for it in JoltPhysicsC.cpp, with a public interface for setting debug renderer callbacks by providing a debug renderer object (whose vtable would then get copied into the global one), or something to that effect.

Speaking of which, it's odd that in JPH there can only ever be one debug renderer instantiated, yet the draw methods inside PhysicsSystem still ask for a pointer to a debug renderer, as if you could ever give it a different one.

**Comment by a-day-old-bagel** [comment]
> Compiler won't figure it out - we need to do conditional compiling.
> 
> Something like below should work:
> 
> `my_debug_field: if (debug_renderer) u32 else void,`

Ok, actual real (concise) question that won't turn into rambling edits (hopefully): As a C API, JoltPhysicsC might be called from a myriad of different languages. Is it really good API design to have part of the API conditionally compiled? What if some language has even worse support for that than Zig does? Wouldn't it be better for the API to be unchanging, regardless of C/C++ #defines, but to alter its behavior based on those defines? Something like this, for example:

```C++
#if JPC_DEBUG_RENDERER == 1
JPC_API void
JPC_DebugRenderer_TriangleBatch_AddRef(JPC_DebugRenderer_TriangleBatch *in_batch)
{
    // Actually do the thing
}
#else //JPC_DEBUG_RENDERER
JPC_API void
JPC_DebugRenderer_TriangleBatch_AddRef(JPC_DebugRenderer_TriangleBatch *in_batch)
{
    assert(!"Must compile with JPH_DEBUG_RENDERER defined to use JPC_DebugRenderer_TriangleBatch_AddRef!");
}
#endif //JPC_DEBUG_RENDERER
```

Maybe my version is the actual API design faux pas, I don't really know. But any input would be appreciated.

**Comment by a-day-old-bagel** [comment]
I have made a PR. I think it turned out pretty clean, but let me know if you have any issues with the way it's put together.
