### ISSUE TITLE
zmath API weird to use when not working with 4 dimensions

### ISSUE THREAD

**Issue by KekOnTheWorld** [michal-z/zig-gamedev#265]
Consider the following: I want to calculate the angle between 2 two dimensional vectors. Since most of the functions take only Vec4's or larger I have to construct and deconstruct these vectors.

```ts
// Angle between vectors
const a_4 = .{ a[0], a[1], 0, 0 };
const b_4 = .{ b[0], b[1], 0, 0 };
const angle = zm.acos(
    zm.dot2(a_4, b_4)[0] / zm.length2(a_4)[0] * zm.length2(b_4)[0],
) / 2;
```

This is extremely annoying to work with. Why don't the 2 dimensional functions (like `dot2`, `normalize2`, `length2` etc.) take 2 dimensional vectors as inputs and output 2 dimensional vectors? Is there a design consideration which I am missing here?

**Comment by michal-z** [comment]
`zmath` is low-level SIMD math library, it works directly with hardware registers. The smallest SIMD register size is 128-bits this is why `zmath` uses `Vec4`.

Your code can be simplified:

```zig
const av = zm.normalize2(zm.loadArr2(a));
const bv = zm.normalize2(zm.loadArr2(b));
const anglev = zm.acos(zm.dot2(av, bv));
```

**Comment by KekOnTheWorld** [comment]
Thanks for your response. I wasn't aware of the loadArr2 function, it seams to make things a lot cleaner. Is there a reverse loadArr2 or equivalent too?

**Comment by michal-z** [comment]
Yes, the reverse is `storeArr2()`.
