### ISSUE TITLE
zphysics: manually activate a body

### ISSUE THREAD

**Issue by aSemy** [michal-z/zig-gamedev#291]
hi 👋 

I'm using the C bindings directly (not via zig), and I'd like to be able to manually re-activate a body after it has been deactivated due to inactivity.

I'm adapting the `HelloWorld` test so that when I press space the ball jumps up. Inside the ['safe lock'](https://github.com/michal-z/zig-gamedev/blob/901313555bd22d3d3a23e2f334d22d45913a9253/libs/zphysics/libs/JoltC/JoltPhysicsC_Tests.c#L599-L612) check, I call `JPC_Body_SetLinearVelocity(sphereId, [0, 1, 0])`. 

This works while the ball is in motion, but as soon as it comes to stop on the floor Jolt will put the ball to sleep.

> When objects move too little the body will be put to sleep 
> 
> _https://jrouwe.github.io/JoltPhysics/index.html_

As a workaround I can call `JPC_Body_SetAllowSleeping()`, but this will not re-activate an inactive body, so it must be called _before_ the body is put to sleep. It also means that the body is always active, which causes extra computations.

I assume that re-activating a body can be achieved by using [`BodyInterface::ActivateBody`](https://jrouwe.github.io/JoltPhysics/class_body_interface.html#ab6ccbc72a1df04bd16c5dc5dee7bdf30), however there is no binding for this in [JoltPhysicsC.h](https://github.com/michal-z/zig-gamedev/blob/901313555bd22d3d3a23e2f334d22d45913a9253/libs/zphysics/libs/JoltC/JoltPhysicsC.h). Would it be possible to add a C binding for this?

Thanks for the binding! If I can help, please ask.

**Comment by michal-z** [comment]
Hi,

I've added the bindings you need. Let me know if it works for you.

**Comment by aSemy** [comment]
It works! Thank you very much
