### ISSUE TITLE
zmath: assert prevents reverse depth buffer implementation

### ISSUE THREAD

**Issue by gmodarelli** [michal-z/zig-gamedev#293]
Hello, 

I was implementing reverse depth buffer for our renderer and bumped into this assert from `zmath`
https://github.com/michal-z/zig-gamedev/blob/main/libs/zmath/src/zmath.zig#L2266

I need to pass inverted near and far to implement reverse depth buffer. For now I've patched `zmath` locally, but before contributing a PR I wanted to make sure that I was right :)

**Comment by michal-z** [comment]
Hi,

How much code do we need to change in this function to support inverted-z?

**Comment by gmodarelli** [comment]
We would only need to remove the part of the assertion that asserts `far > near`

**Comment by michal-z** [comment]
Great, so let's remove it.
