### ISSUE TITLE
[zgui] `main.zig` pub usingnamespace breaks zls

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#306]
Hey! 

I just wanted to let you know that the way zgui is set up, with `gui.zig` being a pub usingnamespace, zls cannot provide hover or go to. I'll mention this in the zls discord but if it's not too much trouble could I PR moving the contents of `main.zig` to `gui.zig` to alleviate this issue? 

It may also be happening in other libraries but zgui is the only one I use that has the problem.

**Comment by michal-z** [comment]
Hey!

Could you submit a proposed PR for this? I would like to see how much stuff we need to change.

Thanks
