### ISSUE TITLE
dxc.exe cannot start or run due to incompatibilities with 64-bit versions of windows

### ISSUE THREAD

**Issue by charlie-ht** [michal-z/zig-gamedev#31]
I followed the instructions saying that a `zig build` should be sufficient, but I get this,

![image](https://user-images.githubusercontent.com/14251608/155203172-9ff20784-49ea-431e-a414-c7176d540dec.png)

```
zig env
{
 "zig_exe": "C:\\work\\zig\\zig.exe",
 "lib_dir": "C:\\work\\zig\\lib",
 "std_dir": "C:\\work\\zig\\lib\\std",
 "global_cache_dir": "C:\\Users\\Charles\\AppData\\Local\\zig",
 "version": "0.10.0-dev.895+df38c46be"
}
```

```
Processor	AMD Ryzen 5 4500U with Radeon Graphics            2.38 GHz
Installed RAM	8.00 GB (7.39 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
```
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎30/‎11/‎2021
OS build	22000.493
Experience	Windows Feature Experience Pack 1000.22000.493.0
```

Please let me know if I can provide better information, this project looks great!

**Comment by michal-z** [comment]
Hi and thanks for the report!

Did you clone the repo or downloaded a zip?
This looks like an issue with Git LFS... I will investigate further.

**Comment by charlie-ht** [comment]
Ah, thanks for hint, I didn't follow the README properly.
All works now, amazing job!
