### ISSUE TITLE
col-major matrices

### ISSUE THREAD

**Issue by prime31** [michal-z/zig-gamedev#33]
Awesome work on the lib! I was wondering if you had any plans to support col-major matrices for those of use who aren't on Windows and are stuck without DirectX.

**Comment by michal-z** [comment]
Thanks!
Note that you can already use the lib with other APIs, for example when using OpenGL below code should work jus fine:

```Zig
const mvp = mul(proj, modelview);
// transpose(mvp) should be passed to GLSL
```
There are also right-handed version of some functions for OpenGL and Vulkan - `perspectiveRh`, `lookAtRh`.

**Comment by michal-z** [comment]
Closing for now - feel free to re-open if you want to discuss it further.
