### ISSUE TITLE
Purpleish background on PBR demo

### ISSUE THREAD

**Issue by Srekel** [michal-z/zig-gamedev#34]
I'm guessing this is not intentional? :)

![image](https://user-images.githubusercontent.com/1578924/159158712-58e08784-144b-4fd2-8b5b-cd3301796fd1.png)

**Comment by michal-z** [comment]
Interesting. What graphics card do you have?

**Comment by Srekel** [comment]
Radeon RX 580 should have reasonably up to date drivers. Let me know if I can help in debugging it. :)

(Not at all a priority for me, I just noticed it and thought I'd report it)

**Comment by michal-z** [comment]
Thanks. I will look at it on Monday. Other samples work fine?

**Comment by Srekel** [comment]
Yeah, bindless has the same issue but otherwise works fine.
![image](https://user-images.githubusercontent.com/1578924/159162422-73f80953-82e9-40c8-baac-34f3ad6d4546.png)

**Comment by michal-z** [comment]
@Srekel Can you please update to the latest code and see if it still happens? For now I did this change only for `physically_based_rendering`.

**Comment by Srekel** [comment]
Success :) 
![image](https://user-images.githubusercontent.com/1578924/159905978-363ac00f-51ee-47ec-8b24-7a432b829264.png)

**Comment by michal-z** [comment]
Awesome :)
