### ISSUE TITLE
[zphysics] Character/VirtualCharacter implementation

### ISSUE THREAD

**Issue by a-day-old-bagel** [michal-z/zig-gamedev#343]
Anyone already working on this? Or should I try putting something together. If I do, are there any suggestions about how we want that API to look? Or just a "use your best judgement" sort of thing?

**Comment by Srekel** [comment]
I haven't had time yet and will have a few other things I need to fix first, so I wouldn't be surprised if it's another six months or more away for me. If you get one set up first I'd love to look at it for inspiration.

**Comment by a-day-old-bagel** [comment]
I do have one working on my fork, just haven't PR'd yet since I wasn't sure how much it needed tests written first to be an acceptable PR. Also some methods aren't there yet because I don't use them myself (it's been implemented as-needed).

But I should probably just PR it and address any concerns like that as they arise.

**Comment by michal-z** [comment]
Yes, please make a PR.

**Comment by a-day-old-bagel** [comment]
Sorry, didn't notice your response until now. [I have a PR of all my recent work](https://github.com/michal-z/zig-gamedev/pull/416). I haven't gone over it with a fine-toothed comb like I usually would, but rather just sort of threw it at you. Just a warning.

**Comment by a-day-old-bagel** [comment]
Given that there is now an implementation, even though some methods are yet to be implemented, I think I can close this issue. If someone needs the other methods implemented but doesn't know how to do it themselves, I can help with that in the future.
