### ISSUE TITLE
zsdl: "unable to find Dynamic system library 'SDL2'" when cross-compiling for windows on linux

### ISSUE THREAD

**Issue by scbafk** [michal-z/zig-gamedev#369]
I get the following error when trying to cross-compile to windows from my linux machine:

```
zig build-exe citadel Debug x86_64-windows-gnu: error: error: unable to find Dynamic system library 'SDL2' using strategy 'paths_first'. searched paths:       
  /home/scb/work/citadel/ext-libs/zig-gamedev/libs/zsdl/libs/x86_64-windows-gnu/lib/SDL2.dll
  /home/scb/work/citadel/ext-libs/zig-gamedev/libs/zsdl/libs/x86_64-windows-gnu/lib/SDL2.lib                                                                   
  /home/scb/work/citadel/ext-libs/zig-gamedev/libs/zsdl/libs/x86_64-windows-gnu/lib/libSDL2.a 
```

Excerpt from my build.zig for zsdl related configuration:
```
    const zsdl = @import("ext-libs/zig-gamedev/libs/zsdl/build.zig");
    const zsdl_pkg = zsdl.package(b, target, optimize, .{});                                                                                                   
    zsdl_pkg.link(exe);
```

Building with: `zig build -Dtarget=x86_64-windows-gnu`

I was originally using my own sdl before porting to zsdl. I  noticed the library I originally had for windows compilation was named: `SDL2.lib`. Also above it is searching for `SDL2.dll`, `SDL2.lib`, or `libSDL2.a`. The SDL2 file provided in the windows lib folder by zsdl is named: `libSDL2.dll.a`  I renamed it to `SDL2.lib` and the issue was resolved. 

Things seem to work but I'd like to confirm this is a proper solution.

**Comment by hazeycode** [comment]
I think `lib/` is from the mingw binary release of SDL. The windows release only has SDL2.dll (vendored in `bin/`).

I think we need to look in `bin/` instead in our build.zig: https://github.com/michal-z/zig-gamedev/blob/d48b1abbd8facce124d2f15b7738272718538ee8/libs/zsdl/build.zig#L28C26-L28C94, presumably `lib/` if using mingw? I'm not sure and I can't really check as at the moment I'm not running Windows.

**Comment by michal-z** [comment]
Thanks for the report! This is now fixed.
