### ISSUE TITLE
zgui: Dependency loop compile error

### ISSUE THREAD

**Issue by chip2n** [michal-z/zig-gamedev#371]
Seems to be the same bug as #282. Should the same workaround be applied to `user_callback` here until the compiler bug is fixed?

https://github.com/michal-z/zig-gamedev/blob/e31e3c280e0e00d3a15f56a4364a506169a5ebe5/libs/zgui/src/gui.zig#L3414-L3424

**Comment by hazeycode** [comment]
Hey this seems to be fixed now (using Zig 0.12.0-dev.1871+e426ae43a). Can you confirm that it's working for you?

**Comment by chip2n** [comment]
Yep, it seems to work :+1:

**Comment by hazeycode** [comment]
Thanks!
