### ISSUE TITLE
zgui: Expose slices into DrawList data

### ISSUE THREAD

**Issue by chip2n** [michal-z/zig-gamedev#372]
It would be useful to have functions that return slices into the various buffers of the draw lists. Current design makes it a bit verbose, especially since the `len` functions return `i32` instead of `usize`:

https://github.com/michal-z/zig-gamedev/blob/e31e3c280e0e00d3a15f56a4364a506169a5ebe5/libs/zgui/src/gui.zig#L3465-L3480

I'm down to implement this if it seems reasonable, but I wanted to check in with you first. Should we keep e.g. `getVertexBufferLength` and `getVertexBufferData` and add a `getVertexBufferSlice`, or remove the data/len ones entirely? Does a change like this fit with the general philosophy of the zgui bindings?

I also wonder if they need to be `const` pointers - it seems that it's possible (and useful) to modify this data, for example translate all vertices so they follow a camera.

**Comment by hazeycode** [comment]
> Should we keep e.g. getVertexBufferLength and getVertexBufferData and add a getVertexBufferSlice, or remove the data/len ones entirely? Does a change like this fit with the general philosophy of the zgui bindings?

This seems reasonable to me. I would keep the current fns and add new `getVertexBuffer`, `getIndexBuffer` and `getCmdBuffer` fns.

> I also wonder if they need to be const pointers - it seems that it's possible (and useful) to modify this data, for example translate all vertices so they follow a camera.

You're right. These return types are currently incorrect. The `const`s should be removed to match the underlying API.
