### ISSUE TITLE
zsdl lld error when building

### ISSUE THREAD

**Issue by ScottyOfTime** [michal-z/zig-gamedev#444]
Following the instructions in zsdl (i.e the build.zig instructions) I receive this when building:

```
Build Summary: 4/9 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run example transitive failure
   ├─ zig build-exe example Debug native 1 errors
   └─ install transitive failure
      └─ install example transitive failure
         └─ zig build-exe example Debug native (+3 more reused dependencies)
error: ld.lld: /home/user/zig-project/src/deps/zsdl/libs/x86_64-linux-gnu/lib/libSDL2-2.0.so:1: unknown directive: version
    note: version https://git-lfs.github.com/spec/v1
    note: ^
```

My project is minimal: only using zsdl and zflecs and adding nothing more to my build.zig than what I have followed from instructions.

**Comment by hazeycode** [comment]
Hey do you have git-lfs installed? The bundled libraries need pulling from the LFS. Which is not ideal.

Beyond that, you might also hit this issue with linking bundled dynamic libraries: https://github.com/michal-z/zig-gamedev/issues/312. To work around this for the time being, I install sdl libs into system paths.

**Comment by ScottyOfTime** [comment]
Hey thanks, error was staring straight at me :sweat_smile:. I have the sdl libs installed and got my program working by commenting out the line in the build.zig (for zsdl) that adds the library path for the bundled library (which is a nasty lfs file).
