### ISSUE TITLE
wgpu examples fail on Linux/MacOS

### ISSUE THREAD

**Issue by wilsonk** [michal-z/zig-gamedev#47]
Building the examples on Linux and MacOS today with an updated zig (as of April 17, 2022) works, but the examples won't actually load/run because of these errors:

Linux:
```
Warning: loader_scanned_icd_add: Driver /usr/lib/amdvlk64.so says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
[zgpu] High-performance device has been selected:
[zgpu]   Name: AMD RADV TONGA
[zgpu]   Driver: radv: Mesa 22.0.1
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Vulkan
triangle_wgpu: /home/wilsonk/zig-gamedev/libs/zgpu/libs/imgui/imgui_draw.cpp:2384: bool ImFontAtlasBuildWithStbTruetype(ImFontAtlas *): Assertion `font_offset >= 0 && "FontData is incorrect, or FontNo cannot be found."' failed.
Aborted (core dumped)
```

MacOS:
```
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1
[zgpu]   Driver: Metal driver on macOS Version 11.6.5 (Build 20G527)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal
Assertion failed: (font_offset >= 0 && "FontData is incorrect, or FontNo cannot be found."), function ImFontAtlasBuildWithStbTruetype, file /Users/wilsonk/zig-gamedev/libs/zgpu/libs/imgui/imgui_draw.cpp, line 2384.
Abort trap: 6
```

The Roboto-medium font is in each directory and I can see that relative addressing is being used to find the font file...not sure why this doesn't work. I tried a different font, just in case the Roboto file was corrupted, but ended up with the same error. Any ideas?

**Comment by michal-z** [comment]
Hi,

You need to install Git LFS extension and re-clone.

Thanks,
Michal

**Comment by wilsonk** [comment]
Ugh, I really thought I had lfs installed on these machines (I do on my other Mac and a couple other Linux boxes, but not these newer ones). Sorry to bother.

**Comment by wilsonk** [comment]
Just as a note. The examples both build and run on MacOS and Linux (using release-fast on Linux, as there is a UB without it, as you mentioned on the Discord). Close when you like  :)

**Comment by michal-z** [comment]
Thanks for confirmation and interest in the project!
