### ISSUE TITLE
Shader Interop

### ISSUE THREAD

**Issue by gmodarelli** [michal-z/zig-gamedev#49]
Hello there, I don't think this is really an "issue", but I wanted to know if there are plans to introduce some form of shader interoperability between Zig and HLSL.

I haven't had a need for it until yesterday and my first idea was to declare `struct`s and `DEFINE`s in a C header file and import it in Zig and include it into my HLSL shaders.

Any thoughts on it?
Thank you :)

**Comment by michal-z** [comment]
Hi!

Yes, that should work pretty well. I was using this technique in C++ projects: https://github.com/michal-z/ImageBasedPBR/blob/master/Source/CPUAndGPUCommon.h

You just need to be careful when it comes to offsets of particular struct fields. Sometimes you will have to add padding for C++ structs.

Please try it and let me know if you hit an issue - will try to help.

Thanks,
Michal

**Comment by gmodarelli** [comment]
Thanks for the link!

Absolutely, I'm already adding padding to zig's structs so that I don't forget when I move them to HLSL 😄 
![image](https://user-images.githubusercontent.com/579525/164010779-f17b3f63-600e-4dcb-b39e-53dffc3090ea.png)

I hope I can share something soon here as I'm working on a new sample!

**Comment by michal-z** [comment]
Great, can't wait!

**Comment by michal-z** [comment]
@gmodarelli Should I close this?

**Comment by garettbass** [comment]
I feel like we could pretty easily provide a generic type, e.g.
```zig
UniformStruct(struct { accum_draw_index: u32, mvp: F32x4x4 })
```
That would insert padding as needed to align with the GPU requirements.

**Comment by gmodarelli** [comment]
> @gmodarelli Should I close this issue?

Yes, this can be closed.
