### ISSUE TITLE
Bug | zmath: segfault on returning an anonymous struct directly

### ISSUE THREAD

**Issue by skrax** [michal-z/zig-gamedev#50]
OS: MacOS
System: Intel i7 (Macbook Pro 2019)
Zig Version: 0.9.1
------------------------------------
EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

I am not sure if this is a library issue:

```
// causes a segfault on accesing sc[1] (address is supposedly 0x0?)
pub fn rotationZ(angle: f32) Mat {
    const sc = sincos(angle);
    return .{
        f32x4(sc[1], sc[0], 0.0, 0.0),
        f32x4(-sc[0], sc[1], 0.0, 0.0),
        f32x4(0.0, 0.0, 1.0, 0.0),
        f32x4(0.0, 0.0, 0.0, 1.0),
    };
}
// this 'fixed' version works fine
pub fn rotationZ(angle: f32) Mat {
    const sc = sincos(angle);
    const result = .{
        f32x4(sc[1], sc[0], 0.0, 0.0),
        f32x4(-sc[0], sc[1], 0.0, 0.0),
        f32x4(0.0, 0.0, 1.0, 0.0),
        f32x4(0.0, 0.0, 0.0, 1.0),
    };

    return result;
}
```

**Comment by michal-z** [comment]
What compiler version do you use?

**Comment by michal-z** [comment]
@skrax Can you also run `zig build test` in the project root directory? There are some tests for `rotationZ` and they work fine on my machine (Windows, Linux, x86_64).

**Comment by skrax** [comment]
@michal-z the tests run fine on 0.9.1
I will try checking out 0.10 later

**Comment by michal-z** [comment]
I see, thanks. Test uses `rotationZ` like this:

```zig
    {
        const m0 = matFromAxisAngle(f32x4(0.0, 0.0, 1.0, 0.0), math.pi * 0.333);
        const m1 = rotationZ(math.pi * 0.333);
        try expect(approxEqAbs(m0[0], m1[0], 0.001));
        try expect(approxEqAbs(m0[1], m1[1], 0.001));
        try expect(approxEqAbs(m0[2], m1[2], 0.001));
        try expect(approxEqAbs(m0[3], m1[3], 0.001));
    }
```

**Comment by wilsonk** [comment]
Hello Michal and skrax,

I am getting the error below when trying to run the tests on my M1 Mac mini (Big Sur) with zig master branch built today (0.10.0-dev.1860+7b090df66):  

```bash
 wilsonk  ~  zig-gamedev   main  zig build test -Drelease-fast -Ddawn-from-source=true
All 9 tests passed.
All 4 tests passed.
LLVM Emit Object... error(link): undefined reference to symbol '_sincosf'
error(link):   first referenced in '/Users/wilsonk/zig-gamedev/zig-cache/o/bede7d83f1692d97996a78a4dce04395/test.o'
thread 2335881 panic: attempt to unwrap error: UndefinedSymbolReference
/Users/wilsonk/Downloads/zig/src/link/tapi/yaml.zig:59:28: 0x10337fa83 in link.tapi.yaml.Value.asList (zig1)
        if (self != .list) return error.TypeMismatch;
.
.
.
```
I get the error with or without ``` -Dtarget=aarch64-macos-gnu ``` and in Debug or Release. This does seem to be a problem with zig/macos though, as per this thread: https://github.com/ziglang/zig/issues/10318 

Perhaps this is related to the issue here? Not sure.

Would you like me to open a separate issue for this failing test on macos?

**Comment by michal-z** [comment]
Hi and thanks for the report.

@wilsonk I think that this is a different issue than reported by @skrax .

zmath itself does not use `sincos` provided by Zig - only tests do (zmath has it's own simple implementation of scalar `sincos`).

Tests run fine for @skrax so I think he is hitting an compiler bug specific to his use case.

I think that you are indeed hitting [ziglang/zig#10318](https://github.com/ziglang/zig/issues/10318). Yes, please open a separate issue.

**Comment by michal-z** [comment]
@skrax Can you share more context? How do you call `rotationZ`?

**Comment by skrax** [comment]
@michal-z I just built zig master and it seems to be working great so far. It is in fact a compiler issue, as we have suspected. It seems like SIMD structures are an issue on Apple as of version 0.9.1.
