### ISSUE TITLE
zgpu doesn't catch vulkan load error

### ISSUE THREAD

**Issue by hazeycode** [michal-z/zig-gamedev#60]
When running a program using zgpu in a linux environment where vulkan is not available, a "null" adapter is acquired and the code path for handling the error is not reached.

I see 2 problems here:
1. Dawn should fallback to an OpenGL backend (out of scope for zgpu)
2. mach/gpu produces a Null adapter rather than an error and zgpu tries to treat this as valid

The end result is an empty window and the following stdout would not be visible to an end-user:

```
Error: Couldn't load Vulkan. Searched /home/chris/zig-gamedev/zig-out/bin/libvulkan.so.1, libvulkan.so.1.
    at operator() (/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/libs/dawn/src/dawn/native/vulkan/BackendVk.cpp:201)
    at Initialize (/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/libs/dawn/src/dawn/native/vulkan/BackendVk.cpp:206)
    at Create (/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/libs/dawn/src/dawn/native/vulkan/BackendVk.cpp:168)
    at operator() (/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/libs/dawn/src/dawn/native/vulkan/BackendVk.cpp:423)

[zgpu] High-performance device has been selected:
[zgpu]   Name: Null backend
[zgpu]   Driver: 
[zgpu]   Adapter type: CPU
[zgpu]   Backend type: Null
```

**Comment by michal-z** [comment]
Thanks for the report.

I think that we shouldn't support OpenGL. It can have different performance characteristic and also, as I understand, it is "best effort" implementation in Dawn.

I have added early check on Linux to make sure that Vulkan driver is installed, if it isn't we print error message and exit.

Please let me know what do you think about this solution.

**Comment by hazeycode** [comment]
I agree that relying on Dawn's OpenGL backend to function to any acceptable standard will be more pain than it's worth and that requiring Vulkan is best for zgpu.

Looking at the commit, I think it's a good solution, since the user of zgpu can now handle the error however they deem appropriate for the end-user, i.e. present a system dialog.
