### ISSUE TITLE
Include all Imgui Bindings?

### ISSUE THREAD

**Issue by ckrowland** [michal-z/zig-gamedev#78]
I currently have a build script working for zgpu with the [Zig-ImGui](https://github.com/SpexGuy/Zig-ImGui) library giving me access to all ImGui bindings. It adds the Zig-ImGui library as another submodule in zgpu. Would this be a direction for the project your interested in? I'm building a personal project with this, and eventually want to integrate the ImPlot library as well.

**Comment by michal-z** [comment]
Hi, nice work with integrating Zig-ImGui!

I have decided to not use it for now and gradually expose more and more functionality via `zgui`. I think that Zig-ImGui is very nice and I may change my mind in the future but for now I want to continue with `zgui`.

The idea with `zgui` is to build more 'Ziggy' interface with default args (`.{}`), Zig string formatting (`text("{s}", .{str})`) etc.
