### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by vitalspace** [michal-z/zig-gamedev#88]
![image](https://user-images.githubusercontent.com/29004070/185995402-34675814-2632-4a51-85a1-400ef7009f0a.png)

**Comment by michal-z** [comment]
Project requires [Zig 0.10.0-dev.3027 (master)](https://ziglang.org/download/) or newer to compile.

Looks like you are using older version.

**Comment by vitalspace** [comment]
ty 

![image](https://user-images.githubusercontent.com/29004070/185997713-3a9b047b-ba86-46bf-9c79-cc5aff4ce8a9.png)
