### ISSUE TITLE
git error: Filename too long on Windows when using zig-gamedev as a submodule

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#90]
Please let me know if this is out-of-scope of zig-gamedev, but I just hit this error trying to test my project on Windows.

My project uses zig-gamedev as a submodule within `src/deps`, but when cloning the project recursively, I get an error:

```
C:\Users\foxnne\dev\proj\aftersun\src\deps\zig-gamedev\libs\zgpu\libs\mach-gpu-dawn\libs\dawn\test\tint\unittest\reader\spirv\PreserveFloatCoords_NonArrayed_SpvParserHandleTest_ImageCoordsTest_MakeCoordinateOperandsForImageAccess_0.spvasm.expected.glsl [204ms]
[2022-08-25T19:07:09.305Z] error: unable to create file test/tint/unittest/reader/spirv/PreserveFloatCoords_NonArrayed_SpvParserHandleTest_ImageCoordsTest_MakeCoordinateOperandsForImageAccess_0.spvasm.expected.glsl: Filename too long
```

It appears that there is a really long filename within `mach-gpu-dawn` that, when combined with being several submodules deep ends up hitting the max file length Windows supports. 

Is there a workaround for this, or do you suggest a different way of including `zig-gamedev` in projects? The only other way I can think that wouldn't involve checking in potentially really large files into git, would be to use `build.zig` to download `zig-gamedev` into `src/deps` and use .gitignore to avoid checking it into git at all, but I assume I would still end up hitting a max file length issue there as well. 

Any information would be great, thanks!

**Comment by michal-z** [comment]
That strange. I'm working on a Windows machine and haven't seen this error.

Note that you don't really need Dawn and DirectXShaderCompiler submodules - they are only needed when you compile Dawn from source using: `-Dzgpu-dawn-from-source=true`.

Maybe try to remove those submodules from your project?

**Comment by foxnne** [comment]
Apologies if I'm misunderstanding, but I didn't add those submodules to my project, I simply added `zig-gamedev` as a submodule to my project and cloned recursively, which pulled those submodules in. Is there an intended way to include `zig-gamedev` in my project other than adding as a submodule? I would need to avoid recursively cloning and manage updating submodules one-by-one if I'm understanding correctly to avoid pulling in those other submodules.

**Comment by michal-z** [comment]
I'm not sure why git fetches Dawn and DirectXShaderCompiler submodules for you. Those submodules should be only fetched when `-Dzgpu-dawn-from-source=true` is used.

Personally I really don't like submodules and I try to avoid them at all cost :)

I would suggest copying libs that you need from zig-gamedev to your project. Brucelib is using this approach: https://github.com/hazeycode/brucelib

Please, let me know if it would work for you, otherwise we can come up with a different solution.

**Comment by foxnne** [comment]
I'll follow suit with how Brucelib is doing it then! No problem, just typically when working with dependencies my workflow has been so submodule them so its easy to update them down the road, but I can use a shell script to handle that if need be. I just need to look into how Brucelib handles copying the files in so that `-Dzgpu-dawn-from-source=true` isn't broken because I think just straight copying the libs folder wouldn't keep the submodule within but I'm not sure on that.

The issue is that when using a submodule for `zig-gamedev`, cloning the parent project is typically used with `git clone 'project' --recursive` which recursively goes through all subdirectories and clones all the submodules. Since Dawn and DirectXShaderCompiler are submodules within `zig-gamedev` those get init as well, even though they aren't necessary.

Thanks for your help!

**Comment by michal-z** [comment]
@foxnne I have decided to remove all submodules from the project. You should now be able to use zig-gamedev as a submodule if you liked this approach.

**Comment by foxnne** [comment]
Thanks for letting me know! I'll likely continue forward just copying libs into my project as needed as it's more modular and I don't necessarily need everything for a 2D project. But thank you!
